%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\TwilleysLab\Desktop\Coding\RF_FCO2_USAtf.csv
%
% Auto-generated by MATLAB on 19-Mar-2025 18:26:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FCO2", "TIMESTAMP_END"];
opts.VariableTypes = ["double", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TIMESTAMP_END", "InputFormat", "dd-MMM-yyyy HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
RFFCO2USAtf = readtable("C:\Users\TwilleysLab\Desktop\Coding\RF_FCO2_USAtf_724.csv", opts);


%% Clear temporary variables
clear opts