%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\TwilleysLab\Downloads\qcfluxes_3_20_24to_2_12_25.csv
%
% Auto-generated by MATLAB on 19-Mar-2025 13:51:45

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 85);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TIMESTAMP_END", "DOY", "daytime", "H", "qc_H", "LE", "qc_LE", "co2_flux", "qc_co2_flux", "h2o_flux", "qc_h2o_flux", "ch4_flux", "qc_ch4_flux", "H_strg", "LE_strg", "co2_strg", "h2o_strg", "ch4_strg", "co2_molar_density", "co2_mole_fraction", "co2_mixing_ratio", "h2o_molar_density", "h2o_mole_fraction", "h2o_mixing_ratio", "ch4_molar_density", "ch4_mole_fraction", "ch4_mixing_ratio", "sonic_temperature", "air_temperature", "air_pressure", "air_density", "air_heat_capacity", "air_molar_volume", "ET", "water_vapor_density", "e", "es", "specific_humidity", "RH", "VPD", "Tdew", "u_unrot", "v_unrot", "w_unrot", "u_rot", "v_rot", "w_rot", "wind_speed", "max_wind_speed", "wind_dir", "u", "TKE", "L", "zdL", "bowen_ratio", "T", "air_t_mean", "air_p_mean", "ALB_1_1_1", "LWIN_1_1_1", "LWOUT_1_1_1", "PPFD_1_1_1", "P_RAIN_1_1_1", "RH_1_1_1", "RN_1_1_1", "SHF_1_1_1", "SHF_2_1_1", "SHF_3_1_1", "SWC_1_1_1", "SWC_2_1_1", "SWC_3_1_1", "SWIN_1_1_1", "SWOUT_1_1_1", "TA_1_1_1", "TCNR4_C_1_1_1", "TS_1_1_1", "TS_2_1_1", "TS_3_1_1", "co2_mean", "h2o_mean", "dew_point_mean", "ch4_mean", "TS_4_1_1", "TS_5_1_1", "TS_6_1_1"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TIMESTAMP_END", "InputFormat", "MM/dd/yyyy HH:mm:ss", "DatetimeFormat", "preserveinput");

qcfluxes32024to21225 = readtable("D:\MATLAB\USAtf_Processing\qcfluxes_3_20_24to_2_12_25.csv",opts);
%% Clear temporary variables
clear opts